[0m14:54:08.989515 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067d6a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067e7e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067f0cd0>]}


============================== 14:54:08.992202 | 5f3761e7-aa44-4ec4-b6ce-ef372cded9c2 ==============================
[0m14:54:08.992202 [info ] [MainThread]: Running with dbt=1.8.6
[0m14:54:08.992495 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/raschellecossid/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m14:54:09.002294 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/raschellecossid/.dbt')}
[0m14:54:09.002506 [info ] [MainThread]: Creating dbt configuration folder at 
[0m14:59:45.353062 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10465ce90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104653e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1035171d0>]}


============================== 14:59:45.356449 | fb629eff-cc5d-4013-becb-2d714a16ceb0 ==============================
[0m14:59:45.356449 [info ] [MainThread]: Running with dbt=1.8.6
[0m14:59:45.356733 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/raschellecossid/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:00:25.285056 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/include/starter_project
[0m15:00:25.298093 [info ] [MainThread]: 
Your new dbt project "dbt_core_analysis" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:00:25.298766 [info ] [MainThread]: Setting up your profile.
[0m15:00:41.995220 [info ] [MainThread]: Profile dbt_core_analysis written to /Users/raschellecossid/.dbt/profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m15:00:42.031700 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 56.706306, "process_user_time": 0.578647, "process_kernel_time": 0.112288, "process_mem_max_rss": "109297664", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:00:42.032105 [debug] [MainThread]: Command `dbt init` succeeded at 15:00:42.032035 after 56.71 seconds
[0m15:00:42.032352 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10472cd50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104736150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10088a650>]}
[0m15:00:42.032592 [debug] [MainThread]: Flushing usage events
[0m15:13:36.870744 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b2d590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10806fe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10808bfd0>]}


============================== 15:13:36.874244 | 79d85db9-094e-475a-80e1-943691e886e8 ==============================
[0m15:13:36.874244 [info ] [MainThread]: Running with dbt=1.8.6
[0m15:13:36.874549 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/raschellecossid/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:14:00.290984 [error] [MainThread]: Encountered an error:

[0m15:14:00.297338 [error] [MainThread]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
              ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/task/init.py", line 325, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/task/init.py", line 279, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/raschellecossid/Library/Python/3.11/lib/python/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/raschellecossid/Library/Python/3.11/lib/python/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m15:14:00.300953 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 23.461592, "process_user_time": 0.528966, "process_kernel_time": 0.101452, "process_mem_max_rss": "95436800", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:14:00.301672 [debug] [MainThread]: Command `dbt init` failed at 15:14:00.301539 after 23.46 seconds
[0m15:14:00.302224 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1031c6650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108096490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108076e90>]}
[0m15:14:00.302767 [debug] [MainThread]: Flushing usage events
[0m15:14:24.410428 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104462d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104460d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10447fd90>]}


============================== 15:14:24.414057 | e1e20647-65ef-4355-a923-54d0a5fb8b83 ==============================
[0m15:14:24.414057 [info ] [MainThread]: Running with dbt=1.8.6
[0m15:14:24.414386 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/raschellecossid/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init ecommerce_transaction_analysis_dbt', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:14:24.423834 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/include/starter_project
[0m15:14:24.428446 [info ] [MainThread]: 
Your new dbt project "ecommerce_transaction_analysis_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:14:24.428654 [info ] [MainThread]: Setting up your profile.
[0m15:14:26.484108 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 2.1024358, "process_user_time": 0.565834, "process_kernel_time": 0.115622, "process_mem_max_rss": "111263744", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:14:26.484437 [debug] [MainThread]: Command `dbt init` succeeded at 15:14:26.484375 after 2.10 seconds
[0m15:14:26.484621 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10068e790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10068e750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100732fd0>]}
[0m15:14:26.484792 [debug] [MainThread]: Flushing usage events
[0m15:19:13.182990 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10885d0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10887bd50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1084a2c50>]}


============================== 15:19:13.185812 | 54a5190b-2333-4f8b-8d53-087db20136e9 ==============================
[0m15:19:13.185812 [info ] [MainThread]: Running with dbt=1.8.6
[0m15:19:13.186144 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/raschellecossid/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:19:13.186483 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/raschellecossid/Documents/Ecommerce-Sales-Analysis/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:19:13.188030 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.03359846, "process_user_time": 0.528061, "process_kernel_time": 0.090814, "process_mem_max_rss": "93929472", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:19:13.188326 [debug] [MainThread]: Command `dbt run` failed at 15:19:13.188278 after 0.03 seconds
[0m15:19:13.188530 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10887b6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10887a7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a9e6d0>]}
[0m15:19:13.188698 [debug] [MainThread]: Flushing usage events
[0m15:43:46.558026 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104215150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104217110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103e76c50>]}


============================== 15:43:46.561139 | 602a91ef-2e7d-4e4e-955d-af52de47c90c ==============================
[0m15:43:46.561139 [info ] [MainThread]: Running with dbt=1.8.6
[0m15:43:46.561487 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/raschellecossid/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:43:46.572594 [info ] [MainThread]: dbt version: 1.8.6
[0m15:43:46.572905 [info ] [MainThread]: python version: 3.11.0
[0m15:43:46.573155 [info ] [MainThread]: python path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
[0m15:43:46.573321 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m15:43:46.741130 [info ] [MainThread]: Using profiles dir at /Users/raschellecossid/.dbt
[0m15:43:46.741415 [info ] [MainThread]: Using profiles.yml file at /Users/raschellecossid/.dbt/profiles.yml
[0m15:43:46.741561 [info ] [MainThread]: Using dbt_project.yml file at /Users/raschellecossid/Documents/Ecommerce-Sales-Analysis/dbt_project.yml
[0m15:43:46.741739 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m15:43:46.743475 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.21557434, "process_user_time": 0.584967, "process_kernel_time": 0.127433, "process_mem_max_rss": "110215168", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:43:46.743781 [debug] [MainThread]: Command `dbt debug` failed at 15:43:46.743729 after 0.22 seconds
[0m15:43:46.744008 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104253d50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10430f090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104300690>]}
[0m15:43:46.744226 [debug] [MainThread]: Flushing usage events
